UPDATE customer
SET name="mano"
WHERE ID_customer="1"
UPDATE customer
SET Email="mano@gmail.com"
WHERE ID_customer="1"
UPDATE cart
SET price="5000"
WHERE ID_cart="1"
UPDATE products
SET name="phone"
WHERE ID_product="1"
UPDATE customer
SET address="Cairo"
WHERE ID_customer="1"